models:
  - type: main
    engine: openai
    parameters:
      base_url: https://api.groq.com/openai/v1
      api_key: ${LLM_API_KEY}
      model: llama-3.1-8b-instant

  - type: self_check
    engine: openai
    parameters:
      base_url: https://api.groq.com/openai/v1
      api_key: ${LLM_API_KEY}
      model: llama-3.1-8b-instant

rails:
  input:
    flows:
      - self check input $model=self_check 